Add complex route
nkyazhin/playwright-rq pull request #1
Opened 2021-04-12 09:04 UTC by Kerem356

2021-04-13 13:19 UTC, nkyazhin requested changes

2021-04-13 13:19 UTC, nkyazhin commented on lib/utils.js
> +    }
```
if (!params.complex) { 
  return params;
}
```
for заменить на find
assert.deepStrictEqual на https://lodash.com/docs/4.17.15#isEqual

2021-04-13 13:19 UTC, nkyazhin commented on tests/mocker.spec.js
> +    let page;
лишние пробелы (ниже тоже)

2021-04-13 13:19 UTC, nkyazhin commented on lib/utils.js
> +    }
+ нужены тесты на сам метод getMockParamsByData

2021-04-13 13:56 UTC, Kerem356 commented on tests/mocker.spec.js
> +    let page;
по умолчанию 2?

2021-04-14 06:34 UTC, nkyazhin commented on tests/mocker.spec.js
> +    let page;
да

2021-04-14 07:37 UTC, Kerem356 commented on lib/utils.js
> +    }
it('call with complex filter') тест покрывает логику работы с complex, а остальные тесты покрывают логику работы "прокси"

2021-04-14 08:44 UTC, merged